
import { Property, Testimonial, PropertyType, Development } from './types';

// FIX: Added icon properties to NAV_LINKS to be used in the Header component.
export const NAV_LINKS = [
  { name: 'Home', path: '/', icon: 'fa-solid fa-house' },
  { name: 'Buy', path: '/buy', icon: 'fa-solid fa-house-signal' },
  { name: 'Rent', path: '/rent', icon: 'fa-solid fa-key' },
  { name: 'BTR', path: '/btr', icon: 'fa-solid fa-city' },
  { name: 'Developments', path: '/developments', icon: 'fa-solid fa-building-user' },
  { name: 'Funding', path: '/funding', icon: 'fa-solid fa-hand-holding-dollar' },
  { name: 'Contact', path: '/contact', icon: 'fa-solid fa-envelope' },
];

export const MOCK_PROPERTIES: Property[] = [
  { 
    id: 1, 
    title: 'Luxury Villa in Airport Hills', 
    price: 1200000, 
    type: PropertyType.Detached, 
    bedrooms: 5, 
    bathrooms: 6, 
    location: 'Accra, Ghana', 
    imageUrl: 'https://placehold.co/800x600/2c3e50/ffffff?text=Luxury+Villa', 
    for: 'buy',
    description: 'An exquisite 5-bedroom villa in the prestigious Airport Hills gated community. Features a private pool, a home cinema, and state-of-the-art security systems. Perfect for discerning buyers seeking luxury and tranquility.',
    galleryImages: ['https://placehold.co/800x600/2c3e50/ffffff?text=Pool', 'https://placehold.co/800x600/2c3e50/ffffff?text=Living+Room', 'https://placehold.co/800x600/2c3e50/ffffff?text=Kitchen'],
    amenities: [
        { name: 'Ghana International School', type: 'school', distance: '1.2km' },
        { name: 'Kotoka International Airport', type: 'transport', distance: '3.5km' },
        { name: '37 Military Hospital', type: 'hospital', distance: '2.5km' },
        { name: 'Accra Mall', type: 'shop', distance: '4.0km' },
    ],
    virtualTourUrl: 'https://my.matterport.com/show/?m=uRGXgoiYk9f',
    latitude: 5.606,
    longitude: -0.171,
    priceHistory: [
        { date: '2022-06-01', price: 1100000 },
        { date: '2023-01-10', price: 1150000 },
        { date: '2024-05-20', price: 1200000 },
    ],
    floorPlanUrl: 'https://images.adsttc.com/media/images/5f75/1de3/63c0/17bc/c800/0154/large_jpg/FP-B.jpg?1601510871',
  },
  { 
    id: 2, 
    title: 'Modern Apartment Downtown', 
    price: 3500, 
    type: PropertyType.Apartment, 
    bedrooms: 2, 
    bathrooms: 2, 
    location: 'Osu, Accra', 
    imageUrl: 'https://placehold.co/800x600/2c3e50/ffffff?text=Modern+Apartment', 
    for: 'rent',
    description: 'A chic and modern 2-bedroom apartment in the vibrant heart of Osu. Offers stunning city views, access to a rooftop pool and gym, and is just steps away from top restaurants and shops.',
    galleryImages: ['https://placehold.co/800x600/2c3e50/ffffff?text=Interior', 'https://placehold.co/800x600/2c3e50/ffffff?text=Balcony', 'https://placehold.co/800x600/2c3e50/ffffff?text=Rooftop+Pool'],
    amenities: [
        { name: 'Osu Oxford Street', type: 'shop', distance: '200m' },
        { name: 'Labadi Beach', type: 'park', distance: '3.0km' },
        { name: 'Ako-Adjei Interchange', type: 'transport', distance: '1.0km' },
        { name: 'Nyaho Medical Centre', type: 'hospital', distance: '2.2km'},
    ],
    latitude: 5.556,
    longitude: -0.183,
    priceHistory: [
        { date: '2023-01-01', price: 3200 },
        { date: '2023-07-01', price: 3400 },
        { date: '2024-03-01', price: 3500 },
    ],
    floorPlanUrl: 'https://i.pinimg.com/originals/9c/85/55/9c8555de8222830f3ba4a1a3b37914fd.jpg',
  },
  { 
    id: 3, 
    title: 'Cozy Semi-Detached House', 
    price: 450000, 
    type: PropertyType.SemiDetached, 
    bedrooms: 3, 
    bathrooms: 3, 
    location: 'East Legon, Accra', 
    imageUrl: 'https://placehold.co/800x600/2c3e50/ffffff?text=Semi-Detached', 
    for: 'buy',
    description: 'A charming and well-maintained 3-bedroom semi-detached house in a quiet residential area of East Legon. Features a lovely garden, a modern kitchen, and ample parking space. Ideal for families.',
    galleryImages: ['https://placehold.co/800x600/2c3e50/ffffff?text=Garden', 'https://placehold.co/800x600/2c3e50/ffffff?text=Living+Room', 'https://placehold.co/800x600/2c3e50/ffffff?text=Kitchen'],
    amenities: [
        { name: 'A&C Mall', type: 'shop', distance: '1.5km' },
        { name: 'American International School', type: 'school', distance: '2.0km' },
        { name: 'Legon Botanical Gardens', type: 'park', distance: '4.5km'},
    ],
    virtualTourUrl: 'https://my.matterport.com/show/?m=uRGXgoiYk9f',
    latitude: 5.650,
    longitude: -0.181,
    priceHistory: [
        { date: '2022-08-15', price: 420000 },
        { date: '2023-05-20', price: 435000 },
        { date: '2024-04-01', price: 450000 },
    ],
  },
  { 
    id: 4, 
    title: 'Spacious Penthouse with a View', 
    price: 8000, 
    type: PropertyType.Penthouse, 
    bedrooms: 4, 
    bathrooms: 4, 
    location: 'Cantonments, Accra', 
    imageUrl: 'https://placehold.co/800x600/2c3e50/ffffff?text=Penthouse', 
    for: 'rent',
    description: 'Experience luxury living in this expansive 4-bedroom penthouse in Cantonments. Boasts panoramic city views from a large private terrace, high-end finishes, and access to exclusive building amenities.',
    galleryImages: ['https://placehold.co/800x600/2c3e50/ffffff?text=Living+Room', 'https://placehold.co/800x600/2c3e50/ffffff?text=Bedroom', 'https://placehold.co/800x600/2c3e50/ffffff?text=Kitchen'],
    amenities: [
        { name: 'Embassy of the United States', type: 'transport', distance: '500m'},
        { name: 'Morning Star School', type: 'school', distance: '1.0km'},
        { name: 'Koala Shopping Center', type: 'shop', distance: '1.5km'},
    ],
    latitude: 5.578,
    longitude: -0.172,
    priceHistory: [
        { date: '2022-12-01', price: 7500 },
        { date: '2023-06-01', price: 7800 },
        { date: '2024-02-15', price: 8000 },
    ],
    floorPlanUrl: 'https://www.dimensions.com/images/plans/floor-plans-home-apartment-2-bedroom-l-shape-dimensions-L.jpg',
  },
  { 
    id: 5, 
    title: 'Charming Bungalow', 
    price: 300000, 
    type: PropertyType.Bungalow, 
    bedrooms: 2, 
    bathrooms: 2, 
    location: 'Tema, Ghana', 
    imageUrl: 'https://placehold.co/800x600/2c3e50/ffffff?text=Bungalow', 
    for: 'buy',
    description: 'A delightful 2-bedroom bungalow with a spacious compound in a serene part of Tema. This home offers single-level living, a functional layout, and the potential for future expansion.',
    galleryImages: ['https://placehold.co/800x600/2c3e50/ffffff?text=Interior', 'https://placehold.co/800x600/2c3e50/ffffff?text=Living+Room', 'https://placehold.co/800x600/2c3e50/ffffff?text=Backyard'],
    amenities: [
        { name: 'Tema General Hospital', type: 'hospital', distance: '3.0km' },
        { name: 'Tema Motorway Interchange', type: 'transport', distance: '5.0km' },
        { name: 'Sakumono Beach', type: 'park', distance: '6.0km' },
    ],
    latitude: 5.666,
    longitude: -0.016,
    priceHistory: [
        { date: '2022-02-01', price: 280000 },
        { date: '2023-03-01', price: 290000 },
        { date: '2024-01-10', price: 300000 },
    ],
  },
  { 
    id: 6, 
    title: 'Family Terraced Home', 
    price: 550000, 
    type: PropertyType.Terraced, 
    bedrooms: 4, 
    bathrooms: 3, 
    location: 'Spintex, Accra', 
    imageUrl: 'https://placehold.co/800x600/2c3e50/ffffff?text=Terraced+Home', 
    for: 'buy',
    description: 'A modern 4-bedroom terraced home perfect for a growing family. Located in a secure community with shared amenities, this property offers a great balance of comfort, style, and convenience.',
    galleryImages: ['https://placehold.co/800x600/2c3e50/ffffff?text=Interior', 'https://placehold.co/800x600/2c3e50/ffffff?text=Family+Kitchen', 'https://placehold.co/800x600/2c3e50/ffffff?text=Community+Space'],
    amenities: [
        { name: 'Junction Shopping Mall', type: 'shop', distance: '3.0km' },
        { name: 'Galaxy International School', type: 'school', distance: '2.5km' },
        { name: 'Lister Hospital and Fertility Centre', type: 'hospital', distance: '4.0km' },
        { name: 'Accra-Tema Motorway', type: 'transport', distance: '1.5km' },
    ],
    virtualTourUrl: 'https://my.matterport.com/show/?m=uRGXgoiYk9f',
    latitude: 5.618,
    longitude: -0.103,
    priceHistory: [
        { date: '2022-09-01', price: 525000 },
        { date: '2023-04-15', price: 540000 },
        { date: '2024-03-20', price: 550000 },
    ],
    floorPlanUrl: 'https://conceptdraw.com/a1619c3/p3/preview/640/crc--home-plan-floor-plan.png--diagram-flowchart-example.png',
  },
  { 
    id: 7, 
    title: 'Stylish Duplex Penthouse', 
    price: 2500000, 
    type: PropertyType.DuplexPenthouse, 
    bedrooms: 5, 
    bathrooms: 6, 
    location: 'Airport Residential', 
    imageUrl: 'https://placehold.co/800x600/2c3e50/ffffff?text=Duplex+Penthouse', 
    for: 'buy',
    description: 'The epitome of luxury, this two-level duplex penthouse offers unparalleled space and sophistication. Featuring a double-height living room, private rooftop jacuzzi, and bespoke interior design.',
    galleryImages: ['https://placehold.co/800x600/2c3e50/ffffff?text=Living+Room', 'https://placehold.co/800x600/2c3e50/ffffff?text=Rooftop+Jacuzzi', 'https://placehold.co/800x600/2c3e50/ffffff?text=Bedroom'],
    amenities: [
        { name: 'Marina Mall', type: 'shop', distance: '800m' },
        { name: 'Nyaho Medical Centre', type: 'hospital', distance: '1.2km' },
        { name: 'Kotoka International Airport', type: 'transport', distance: '2.0km' },
    ],
    latitude: 5.608,
    longitude: -0.179,
    priceHistory: [
        { date: '2022-05-10', price: 2300000 },
        { date: '2023-02-20', price: 2400000 },
        { date: '2024-06-01', price: 2500000 },
    ],
  },
  { 
    id: 8, 
    title: 'Affordable Maisonette', 
    price: 280000, 
    type: PropertyType.Maisonette, 
    bedrooms: 3, 
    bathrooms: 2, 
    location: 'Adenta, Accra', 
    imageUrl: 'https://placehold.co/800x600/2c3e50/ffffff?text=Maisonette', 
    for: 'buy',
    description: 'An excellent opportunity for first-time buyers. This 3-bedroom maisonette in Adenta offers comfortable living at an affordable price point, with its own private entrance and living space split over two floors.',
    galleryImages: ['https://placehold.co/800x600/2c3e50/ffffff?text=Interior', 'https://placehold.co/800x600/2c3e50/ffffff?text=Kitchen', 'https://placehold.co/800x600/2c3e50/ffffff?text=Bedroom'],
    amenities: [
        { name: 'Adenta Shopping Center', type: 'shop', distance: '1.0km' },
        { name: 'Frafraha Health Center', type: 'hospital', distance: '2.5km' },
        { name: 'Main road transport', type: 'transport', distance: '500m' },
    ],
    latitude: 5.700,
    longitude: -0.176,
    priceHistory: [
        { date: '2023-01-01', price: 265000 },
        { date: '2023-08-01', price: 275000 },
        { date: '2024-04-10', price: 280000 },
    ],
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
    { id: 1, name: 'Ama Serwaa', location: 'Accra', comment: 'VistaTouch Homes helped my family find our dream home. The process was smooth and professional. Highly recommended!', avatarUrl: 'https://placehold.co/100x100/c9a227/ffffff?text=AS' },
    { id: 2, name: 'John Mensah', location: 'Kumasi', comment: 'Their attention to detail and commitment to quality is unmatched. We are so happy with our new property.', avatarUrl: 'https://placehold.co/100x100/c9a227/ffffff?text=JM' },
    { id: 3, name: 'Femi Adebayo', location: 'Lagos, Nigeria', comment: 'As an investor, I found their BTR options to be excellent. Great returns and hassle-free management.', avatarUrl: 'https://placehold.co/100x100/c9a227/ffffff?text=FA' },
];

export const MOCK_DEVELOPMENTS: Development[] = [
    { id: 1, name: 'Vista Gardens', location: 'Aburi, Ghana', status: 'Current', description: 'An exclusive gated community offering serene living with modern amenities, nestled in the beautiful Aburi mountains.', imageUrl: 'https://placehold.co/600x400/2c3e50/ffffff?text=Vista+Gardens' },
    { id: 2, name: 'Coastal Point', location: 'Prampram, Ghana', status: 'Upcoming', description: 'Stunning beachfront properties with breathtaking ocean views. A perfect blend of luxury and tranquility.', imageUrl: 'https://placehold.co/600x400/2c3e50/ffffff?text=Coastal+Point' },
    { id: 3, name: 'Cityscape Towers', location: 'Accra, Ghana', status: 'Completed', description: 'A landmark residential tower in the heart of Accra, offering sophisticated urban living.', imageUrl: 'https://placehold.co/600x400/2c3e50/ffffff?text=Cityscape+Towers' },
];
